import {
  templateCEO,
  fashionTemp4,
  fashionTemp5,
  SalesRepresentative,
  FinancialExpert,
  FashionDesigner2,
  GraphicDesigner1,
  templateMarket,
  digitalMarketingTemp,
  FlightAttendant1,
  graphicDesignerTemp,
  SocialSpecialist,
  TemplateBabySitter,
  hybridTemplate,
  DigitalMarkTemp2,
  fashionTemp1,
  GraphicDesigner2,
  template5,
  marketingManager1,
  designerTemplate,
  aaronGraphicTemp,
  GraphicDesigner8,
  marketingManager,
  GraphicDesigner3,
  harumiGraphicTemp,
  TemplateContentCreater,
  ExecutiveTemp,
  graphicDesigner,
  StudentTemplate,
  TechTemplate,
  SoftEngineer,
  fashionTemp,
  CollegeTemp,
  simpleTempDesign,
  templatebrand,
  graphTemplate,
  SkillBaseTemp,
  FashionDesigner,
  NovoResumeTemplate,
  // AhsanTemplate1,
} from "../../templates";
import AhsanTemplate1 from "../../templates/AhsanTemplate1";
export const CUSTOM_TEMP_DATA = [
  {
    id: "dhqAtIa3jaWjxddw",
    href: "/templates/dhqAtIa3jaWjxddw",
    src: "/NovoResumeTemplate.png",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Executive",
    component: NovoResumeTemplate,
    sections: {
      work: true,

      skills: true,
    },
    category: {
      categoryID: "1",
      totalCategory: "6",
      categoryName: "Executive",
    },
  },
  {
    id: "l8exLF7L53qddC2E",
    href: "/templates/l8exLF7L53qddC2E",
    src: "/NovoResumeTemplate.png",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Executive",
    component: AhsanTemplate1,
    sections: {
      work: true,

      skills: true,
      education: true,
      organization: true,
    },
    category: {
      categoryID: "1",
      totalCategory: "6",
      categoryName: "Executive",
    },
    colorLength: 3,
  },
  {
    id: "zyCeSJJ2A8fEGNRx",
    href: "/templates/zyCeSJJ2A8fEGNRx",
    src: "/realTemp1.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Combined",
    component: templateCEO,
    sections: {
      work: true,
      education: true,
      languages: true,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "1",
      totalCategory: "6",
      categoryName: "Graphic Designer",
    },
  },
  {
    id: "ny1FF7ED91mc6i2k",
    href: "/templates/ny1FF7ED91mc6i2k",
    src: "/realTemp2.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Minimalist",
    component: fashionTemp5,
    sections: {
      work: true,
      education: true,
      languages: true,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "2",
      totalCategory: "6",
      categoryName: "Graphic Designer",
    },
  },
  {
    id: "7UM1U7FJgAQ5sjWD",
    href: "/templates/7UM1U7FJgAQ5sjWD",
    src: "/realTemp3.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Traditional",
    component: fashionTemp4,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: false,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "3",
      totalCategory: "6",
      categoryName: "Graphic Designer",
    },
  },
  {
    id: "ovIeX2yz4B7V1y0G",
    href: "/templates/ovIeX2yz4B7V1y0G",
    src: "/realTemp4.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "IT",
    component: SalesRepresentative,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: true,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "4",
      totalCategory: "6",
      categoryName: "Graphic Designer",
    },
  },
  {
    id: "9H2XODEcK2Aibm5d",
    href: "/templates/9H2XODEcK2Aibm5d",
    src: "/realTemp5.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Tech",
    component: FinancialExpert,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: true,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "5",
      totalCategory: "6",
      categoryName: "Graphic Designer",
    },
  },
  {
    id: "b5BJwQR7sCmlADl5",
    href: "/templates/b5BJwQR7sCmlADl5",
    src: "/realTemp6.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Skill-Based",
    component: FashionDesigner2,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "6",
      totalCategory: "6",
      categoryName: "Graphic Designer",
    },
  },
  {
    id: "UaMsr4yxtyAJ0d9T",
    href: "/templates/UaMsr4yxtyAJ0d9T",
    src: "/realTemp7.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Basic",
    component: GraphicDesigner1,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "1",
      totalCategory: "3",
      categoryName: "Creative",
    },
  },
  {
    id: "Z8T9Wg5LoA7Ihbsq",
    href: "/templates/Z8T9Wg5LoA7Ihbsq",
    src: "/realTemp8.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Executive",
    component: templateMarket,
    sections: {
      work: true,
      education: true,
      languages: true,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: true,
    },
    category: {
      categoryID: "2",
      totalCategory: "3",
      categoryName: "Creative",
    },
  },
  {
    id: "pSJl09vc4C39lNL3",
    href: "/templates/pSJl09vc4C39lNL3",
    src: "/realTemp9.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "General",
    component: digitalMarketingTemp,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "3",
      totalCategory: "3",
      categoryName: "Creative",
    },
  },
  {
    id: "MTmaNZdZrNEMy0v0",
    href: "/templates/MTmaNZdZrNEMy0v0",
    src: "/realTemp10.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Hybird",
    component: FlightAttendant1,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: true,
    },
    category: {
      categoryID: "1",
      totalCategory: "7",
      categoryName: "Fashion Designer",
    },
  },
  {
    id: "QbnlV2ff7hB3mbdx",
    href: "/templates/QbnlV2ff7hB3mbdx",
    src: "/realTemp11.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Creative",
    component: graphicDesignerTemp,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: true,
      certificate: false,
    },
    category: {
      categoryID: "2",
      totalCategory: "7",
      categoryName: "Fashion Designer",
    },
  },
  {
    id: "PhhchnzxtXfKZXBz",
    href: "/templates/PhhchnzxtXfKZXBz",
    src: "/realTemp12.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Functional",
    component: SocialSpecialist,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "3",
      totalCategory: "7",
      categoryName: "Fashion Designer",
    },
  },
  {
    id: "Mmq0HbjSLc364GmS",
    href: "/templates/Mmq0HbjSLc364GmS",
    src: "/realTemp13.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Modren",
    component: TemplateBabySitter,
    sections: {
      work: true,
      education: true,
      languages: true,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "4",
      totalCategory: "7",
      categoryName: "Fashion Designer",
    },
  },
  {
    id: "d9Ow8i0HO4dP9FMG",
    href: "/templates/d9Ow8i0HO4dP9FMG",
    src: "/realTemp14.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Professional",
    component: hybridTemplate,
    sections: {
      work: true,
      education: true,
      languages: true,
      skills: true,
      projects: true,
      references: false,
      organization: true,
      interest: true,
      certificate: true,
    },
    category: {
      categoryID: "5",
      totalCategory: "7",
      categoryName: "Fashion Designer",
    },
  },
  {
    id: "vn6uST13L2DZbKXe",
    href: "/templates/vn6uST13L2DZbKXe",
    src: "/realTemp15.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "College",
    component: DigitalMarkTemp2,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "6",
      totalCategory: "7",
      categoryName: "Fashion Designer",
    },
  },
  {
    id: "5RpawNwFi49M8BrR",
    href: "/templates/5RpawNwFi49M8BrR",
    src: "/realTemp16.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Simple",
    component: fashionTemp1,
    sections: {
      work: true,
      education: true,
      languages: true,
      skills: true,
      projects: false,
      references: true,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "7",
      totalCategory: "7",
      categoryName: "Fashion Designer",
    },
  },
  {
    id: "pC5lVexxlHtEY2v2",
    href: "/templates/pC5lVexxlHtEY2v2",
    src: "/realTemp17.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Creative",
    component: GraphicDesigner2,
    sections: {
      work: true,
      education: true,
      languages: true,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: true,
      certificate: false,
    },
    category: {
      categoryID: "1",
      totalCategory: "4",
      categoryName: "Digital Marketing",
    },
  },
  {
    id: "UKkFhQx6Qe7JsEXT",
    href: "/templates/UKkFhQx6Qe7JsEXT",
    src: "/realTemp18.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Hybird",
    component: template5,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "2",
      totalCategory: "4",
      categoryName: "Digital Marketing",
    },
  },
  {
    id: "zApetir0shFU3R40",
    href: "/templates/zApetir0shFU3R40",
    src: "/realTemp19.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Minimalist",
    component: marketingManager1,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "3",
      totalCategory: "4",
      categoryName: "Digital Marketing",
    },
  },
  {
    id: "6iz8Y7EFbpAos1dn",
    href: "/templates/6iz8Y7EFbpAos1dn",
    src: "/realTemp20.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Traditional",
    component: designerTemplate,
    sections: {
      work: true,
      education: true,
      languages: true,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: true,
      certificate: false,
    },
    category: {
      categoryID: "4",
      totalCategory: "4",
      categoryName: "Digital Marketing",
    },
  },

  {
    id: "dhqAtIa3jaWjxQLb",
    href: "/templates/dhqAtIa3jaWjxQLb",
    src: "/realTemp21.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Executive",
    component: aaronGraphicTemp,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: true,
      interest: true,
      certificate: false,
    },
    category: {
      categoryID: "1",
      totalCategory: "6",
      categoryName: "Executive",
    },
  },
  {
    id: "q7I7S5FySY1L035S",
    href: "/templates/q7I7S5FySY1L035S",
    src: "/realTemp22.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Modren",
    component: GraphicDesigner8,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "2",
      totalCategory: "6",
      categoryName: "Executive",
    },
  },
  {
    id: "ZmNpNzLENZPooOwP",
    href: "/templates/ZmNpNzLENZPooOwP",
    src: "/realTemp23.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "IT",
    component: marketingManager,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: true,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "3",
      totalCategory: "6",
      categoryName: "Executive",
    },
  },
  {
    id: "zY7eR3FNn1HaM2Kd",
    href: "/templates/zY7eR3FNn1HaM2Kd",
    src: "/realTemp24.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Modren",
    component: GraphicDesigner3,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: true,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "4",
      totalCategory: "6",
      categoryName: "Executive",
    },
  },
  {
    id: "0S4gN5d6gsN4xFd2",
    href: "/templates/0S4gN5d6gsN4xFd2",
    src: "/realTemp25.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Classic",
    component: harumiGraphicTemp,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "5",
      totalCategory: "6",
      categoryName: "Executive",
    },
  },
  {
    id: "2HU7Uuw10GMgVWgJ",
    href: "/templates/2HU7Uuw10GMgVWgJ",
    src: "/realTemp26.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Executive",
    component: TemplateContentCreater,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: false,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "6",
      totalCategory: "6",
      categoryName: "Executive",
    },
  },
  {
    id: "a8e9GJtWwOAIbAVf",
    href: "/templates/a8e9GJtWwOAIbAVf",
    src: "/realTemp27.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Simple",
    component: ExecutiveTemp,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: true,
      references: false,
      organization: true,
      interest: true,
      certificate: true,
    },
    category: {
      categoryID: "1",
      totalCategory: "3",
      categoryName: "Basic",
    },
  },
  {
    id: "4WEhJ5hAXOIcASUB",
    href: "/templates/4WEhJ5hAXOIcASUB",
    src: "/realTemp28.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Professional",
    component: graphicDesigner,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "2",
      totalCategory: "3",
      categoryName: "Basic",
    },
  },
  {
    id: "8xDcvDwe76xjzVG3",
    href: "/templates/8xDcvDwe76xjzVG3",
    src: "/realTemp29.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "General",
    component: StudentTemplate,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "3",
      totalCategory: "3",
      categoryName: "Basic",
    },
  },
  {
    id: "3JeA53zVHMSQsOay",
    href: "/templates/3JeA53zVHMSQsOay",
    src: "/realTemp30.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Skill-Based",
    component: TechTemplate,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: true,
      references: false,
      organization: true,
      interest: true,
      certificate: true,
    },
    category: {
      categoryID: "1",
      totalCategory: "4",
      categoryName: "Skill-Based",
    },
  },
  {
    id: "6nJppDLrOJST3qF2",
    href: "/templates/6nJppDLrOJST3qF2",
    src: "/realTemp31.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Professional",
    component: SoftEngineer,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "1",
      totalCategory: "5",
      categoryName: "General",
    },
  },
  {
    id: "aacKzXcwGUZADCut",
    href: "/templates/aacKzXcwGUZADCut",
    src: "/realTemp32.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "General",
    component: fashionTemp,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "2",
      totalCategory: "5",
      categoryName: "General",
    },
  },
  {
    id: "DkXlwWNOhGxOYVIN",
    href: "/templates/DkXlwWNOhGxOYVIN",
    src: "/realTemp33.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Simple",
    component: CollegeTemp,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: true,
      references: false,
      organization: true,
      interest: true,
      certificate: true,
    },
    category: {
      categoryID: "2",
      totalCategory: "4",
      categoryName: "Skill-Based",
    },
  },
  {
    id: "Dd7HVIibnPERnyhy",
    href: "/templates/Dd7HVIibnPERnyhy",
    src: "/realTemp34.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Hybird",
    component: simpleTempDesign,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: true,
      references: false,
      organization: true,
      interest: true,
      certificate: true,
    },
    category: {
      categoryID: "3",
      totalCategory: "4",
      categoryName: "Skill-Based",
    },
  },
  {
    id: "qUv6wvZZDD75QZ5c",
    href: "/templates/qUv6wvZZDD75QZ5c",
    src: "/realTemp35.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Modren",
    component: templatebrand,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "3",
      totalCategory: "5",
      categoryName: "General",
    },
  },
  {
    id: "XziZdLJgLdEOFB3j",
    href: "/templates/XziZdLJgLdEOFB3j",
    src: "/realTemp36.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "General",
    component: graphTemplate,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "4",
      totalCategory: "5",
      categoryName: "General",
    },
  },
  {
    id: "sBpVCiYIojHRtGlh",
    href: "/templates/sBpVCiYIojHRtGlh",
    src: "/realTemp37.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Skill-Based",
    component: SkillBaseTemp,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: true,
      references: false,
      organization: true,
      interest: true,
      certificate: true,
    },
    category: {
      categoryID: "4",
      totalCategory: "4",
      categoryName: "Skill-Based",
    },
  },
  {
    id: "yrXn4MHXPhkKy5Xf",
    href: "/templates/yrXn4MHXPhkKy5Xf",
    src: "/realTemp38.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Classic",
    component: FashionDesigner,
    sections: {
      work: true,
      education: true,
      languages: true,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
    category: {
      categoryID: "5",
      totalCategory: "5",
      categoryName: "General",
    },
  },
];
