import {
  templateCEO,
  fashionTemp4,
  fashionTemp5,
  SalesRepresentative,
  FinancialExpert,
  FashionDesigner2,
  GraphicDesigner1,
  templateMarket,
  digitalMarketingTemp,
  FlightAttendant1,
  graphicDesignerTemp,
  SocialSpecialist,
  TemplateBabySitter,
  hybridTemplate,
  DigitalMarkTemp2,
  fashionTemp1,
  GraphicDesigner2,
  template5,
  marketingManager1,
  designerTemplate,
  aaronGraphicTemp,
  GraphicDesigner8,
  marketingManager,
  GraphicDesigner3,
  harumiGraphicTemp,
  TemplateContentCreater,
  ExecutiveTemp,
  graphicDesigner,
  StudentTemplate,
  TechTemplate,
  SoftEngineer,
  fashionTemp,
  CollegeTemp,
  simpleTempDesign,
  templatebrand,
  graphTemplate,
  SkillBaseTemp,
  FashionDesigner,
} from "../../templates";

export const CUSTOM_TEMP_DATA = [
  {
    id: "zyCeSJJ2A8fEGNRx",
    href: "/templates/zyCeSJJ2A8fEGNRx",
    src: "/Chief_Exclusive_Office.jpg",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Combined",
    component: templateCEO,
    sections: {
      work: true,
      education: true,
      languages: true,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "ny1FF7ED91mc6i2k",
    href: "/templates/ny1FF7ED91mc6i2k",
    src: "/FashTemp5.png",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Minimalist",
    component: fashionTemp5,
    sections: {
      work: true,
      education: true,
      languages: true,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "7UM1U7FJgAQ5sjWD",
    href: "/templates/7UM1U7FJgAQ5sjWD",
    src: "/FashTemp4.png",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Traditional",
    component: fashionTemp4,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: false,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "ovIeX2yz4B7V1y0G",
    href: "/templates/ovIeX2yz4B7V1y0G",
    src: "/SalesRepresentive2n.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "IT",
    component: SalesRepresentative,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: true,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "9H2XODEcK2Aibm5d",
    href: "/templates/9H2XODEcK2Aibm5d",
    src: "/FinancialAnalyst.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Tech",
    component: FinancialExpert,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: true,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "b5BJwQR7sCmlADl5",
    href: "/templates/b5BJwQR7sCmlADl5",
    src: "/FashionDesigner2n.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Skill-Based",
    component: FashionDesigner2,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "UaMsr4yxtyAJ0d9T",
    href: "/templates/UaMsr4yxtyAJ0d9T",
    src: "/GraphicDesigner12n.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Basic",
    component: GraphicDesigner1,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "Z8T9Wg5LoA7Ihbsq",
    href: "/templates/Z8T9Wg5LoA7Ihbsq",
    src: "/TemplateMarket1n.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Executive",
    component: templateMarket,
    sections: {
      work: true,
      education: true,
      languages: true,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: true,
    },
  },
  {
    id: "pSJl09vc4C39lNL3",
    href: "/templates/pSJl09vc4C39lNL3",
    src: "/digitalMarketingTemp.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "General",
    component: digitalMarketingTemp,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "MTmaNZdZrNEMy0v0",
    href: "/templates/MTmaNZdZrNEMy0v0",
    src: "/FlightAttendantTemplate.png",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Hybird",
    component: FlightAttendant1,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: true,
    },
  },
  {
    id: "QbnlV2ff7hB3mbdx",
    href: "/templates/QbnlV2ff7hB3mbdx",
    src: "/graphicTemp.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Creative",
    component: graphicDesignerTemp,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: true,
      certificate: false,
    },
  },
  {
    id: "PhhchnzxtXfKZXBz",
    href: "/templates/PhhchnzxtXfKZXBz",
    src: "/socialMediaSpecialist.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Functional",
    component: SocialSpecialist,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "Mmq0HbjSLc364GmS",
    href: "/templates/Mmq0HbjSLc364GmS",
    src: "/BabySitterTemplate.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Modren",
    component: TemplateBabySitter,
    sections: {
      work: true,
      education: true,
      languages: true,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "d9Ow8i0HO4dP9FMG",
    href: "/templates/d9Ow8i0HO4dP9FMG",
    src: "/Hybrid_Template_Design.png",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Professional",
    component: hybridTemplate,
    sections: {
      work: true,
      education: true,
      languages: true,
      skills: true,
      projects: true,
      references: false,
      organization: true,
      interest: true,
      certificate: true,
    },
  },
  {
    id: "vn6uST13L2DZbKXe",
    href: "/templates/vn6uST13L2DZbKXe",
    src: "/DigitalMarketingTemp2.png",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "College",
    component: DigitalMarkTemp2,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "5RpawNwFi49M8BrR",
    href: "/templates/5RpawNwFi49M8BrR",
    src: "/FashionDesigner1.png",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Simple",
    component: fashionTemp1,
    sections: {
      work: true,
      education: true,
      languages: true,
      skills: true,
      projects: false,
      references: true,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "pC5lVexxlHtEY2v2",
    href: "/templates/pC5lVexxlHtEY2v2",
    src: "/gdBanner2.jpg",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Creative",
    component: GraphicDesigner2,
    sections: {
      work: true,
      education: true,
      languages: true,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: true,
      certificate: false,
    },
  },
  {
    id: "UKkFhQx6Qe7JsEXT",
    href: "/templates/UKkFhQx6Qe7JsEXT",
    src: "/GraphicDesigner5.png",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Hybird",
    component: template5,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "zApetir0shFU3R40",
    href: "/templates/zApetir0shFU3R40",
    src: "/MarketingManagerTemp.png",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Minimalist",
    component: marketingManager1,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "6iz8Y7EFbpAos1dn",
    href: "/templates/6iz8Y7EFbpAos1dn",
    src: "/designerTemplate.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Traditional",
    component: designerTemplate,
    sections: {
      work: true,
      education: true,
      languages: true,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: true,
      certificate: false,
    },
  },

  {
    id: "dhqAtIa3jaWjxQLb",
    href: "/templates/dhqAtIa3jaWjxQLb",
    src: "/graphicTemplate.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Executive",
    component: aaronGraphicTemp,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: true,
      interest: true,
      certificate: false,
    },
  },
  {
    id: "q7I7S5FySY1L035S",
    href: "/templates/q7I7S5FySY1L035S",
    src: "/graphDes8.png",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Modren",
    component: GraphicDesigner8,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "ZmNpNzLENZPooOwP",
    href: "/templates/ZmNpNzLENZPooOwP",
    src: "/MarkManager2.png",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "IT",
    component: marketingManager,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: true,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "zY7eR3FNn1HaM2Kd",
    href: "/templates/zY7eR3FNn1HaM2Kd",
    src: "/gdBanner3.jpg",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Modren",
    component: GraphicDesigner3,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: true,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "0S4gN5d6gsN4xFd2",
    href: "/templates/0S4gN5d6gsN4xFd2",
    src: "/harumiTemplate.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Classic",
    component: harumiGraphicTemp,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "2HU7Uuw10GMgVWgJ",
    href: "/templates/2HU7Uuw10GMgVWgJ",
    src: "/ContentCreater.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Executive",
    component: TemplateContentCreater,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: false,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "a8e9GJtWwOAIbAVf",
    href: "/templates/a8e9GJtWwOAIbAVf",
    src: "/ExecTemp.png",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Simple",
    component: ExecutiveTemp,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: true,
      references: false,
      organization: true,
      interest: true,
      certificate: true,
    },
  },
  {
    id: "4WEhJ5hAXOIcASUB",
    href: "/templates/4WEhJ5hAXOIcASUB",
    src: "/graphic.png",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Professional",
    component: graphicDesigner,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "8xDcvDwe76xjzVG3",
    href: "/templates/8xDcvDwe76xjzVG3",
    src: "/studentTemp.png",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "General",
    component: StudentTemplate,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "3JeA53zVHMSQsOay",
    href: "/templates/3JeA53zVHMSQsOay",
    src: "/TechTemp.png",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Skill-Based",
    component: TechTemplate,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: true,
      references: false,
      organization: true,
      interest: true,
      certificate: true,
    },
  },
  {
    id: "6nJppDLrOJST3qF2",
    href: "/templates/6nJppDLrOJST3qF2",
    src: "/softEngr.jpg",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Professional",
    component: SoftEngineer,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "aacKzXcwGUZADCut",
    href: "/templates/aacKzXcwGUZADCut",
    src: "/fashionTemp.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "General",
    component: fashionTemp,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "DkXlwWNOhGxOYVIN",
    href: "/templates/DkXlwWNOhGxOYVIN",
    src: "/CollegeTemp.png",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Simple",
    component: CollegeTemp,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: true,
      references: false,
      organization: true,
      interest: true,
      certificate: true,
    },
  },
  {
    id: "Dd7HVIibnPERnyhy",
    href: "/templates/Dd7HVIibnPERnyhy",
    src: "/simpleTemp.png",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Hybird",
    component: simpleTempDesign,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: true,
      references: false,
      organization: true,
      interest: true,
      certificate: true,
    },
  },
  {
    id: "qUv6wvZZDD75QZ5c",
    href: "/templates/qUv6wvZZDD75QZ5c",
    src: "/BRAND_STRATEGIST.jpg",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Modren",
    component: templatebrand,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "XziZdLJgLdEOFB3j",
    href: "/templates/XziZdLJgLdEOFB3j",
    src: "/fashionDesignerTemp.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "General",
    component: graphTemplate,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
  {
    id: "sBpVCiYIojHRtGlh",
    href: "/templates/sBpVCiYIojHRtGlh",
    src: "/SkilledBaseTemplate.png",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Skill-Based",
    component: SkillBaseTemp,
    sections: {
      work: true,
      education: true,
      languages: false,
      skills: true,
      projects: true,
      references: false,
      organization: true,
      interest: true,
      certificate: true,
    },
  },
  {
    id: "yrXn4MHXPhkKy5Xf",
    href: "/templates/yrXn4MHXPhkKy5Xf",
    src: "/fashionDesigher1n.PNG",
    alt: "Template Not Found",
    height: "200px",
    width: "250px",
    heading: "Classic",
    component: FashionDesigner,
    sections: {
      work: true,
      education: true,
      languages: true,
      skills: true,
      projects: false,
      references: false,
      organization: false,
      interest: false,
      certificate: false,
    },
  },
];
