export const CUSTOM_TEMP_DATA = [
    {
        href: '/templates/templateCEO',
        src: 'Chief_Exclusive_Office.jpg',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/fashionTemp5',
        src: 'FashTemp5.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/fashionTemp4',
        src: 'FashTemp4.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/SalesRepresentative',
        src: 'salesReprentative.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/FinancialExpert',
        src: 'financialAdvisor.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/FashionDesigner2',
        src: 'FashionDesigner2.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/GraphicDesigner1',
        src: 'gdBanner.jpg',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/templateMarket',
        src: 'resumeMarket.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/digitalMarketingTemps/digitalMarketingTemp',
        src: 'digitalMarketingTemp.PNG',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/FlightAttendant1',
        src: 'FlightAttendantTemplate.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/graphicDesignerTemp',
        src: 'graphicTemp.PNG',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/SocialSpecialist',
        src: 'social.jpg',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/TemplateBabySitter',
        src: 'templateBaby.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/hybridTemplate',
        src: 'Hybrid_Template_Design.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/DigitalMarkTemp2',
        src: 'DigitalMarketingTemp2.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/fashionTemp1',
        src: 'FashionDesigner1.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/GraphicDesigner2',
        src: 'gdBanner2.jpg',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/template5',
        src: 'GraphicDesigner5.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/marketingManager1',
        src: 'MarketingManagerTemp.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/designerTemplate',
        src: 'designerTemplate.PNG',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/aaronGraphicTemp',
        src: 'graphicTemplate.PNG',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/GraphicDesigner8',
        src: 'graphDes8.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/marketingManager',
        src: 'MarkManager2.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/GraphicDesigner3',
        src: 'gdBanner3.jpg',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/harumiGraphicTemp',
        src: 'harumiTemplate.PNG',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/TemplateContentCreater',
        src: 'templateContent.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/ExecutiveTemp',
        src: 'ExecTemp.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/graphicDesigner',
        src: 'graphic.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/StudentTemplate',
        src: 'studentTemp.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/TechTemplate',
        src: 'TechTemp.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/softEngineer/SoftEngineer',
        src: 'softEngr.jpg',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/fashionTemps/fashionTemp',
        src: 'fashionTemp.PNG',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/CollegeTemp',
        src: 'CollegeTemp.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/simpleTempDesign',
        src: 'simpleTemp.png',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
    {
        href: '/templates/templatebrand',
        src: 'BRAND_STRATEGIST.jpg',
        alt: 'Template Not Found',
        height: '200px',
        width: '250px',
    },
]