export const TABLE_CONTENT_DATA = [
  {
    label: "The BisResume Content",
    href: "a1",
  },
  {
    label: "Acceptable Use",
    href: "a2",
  },
  {
    label: "Security",
    href: "a3",
  },
  {
    label: "Links To Other Software/Websites/Services",
    href: "a4",
  },
  {
    label: "Warranty and Premium Account",
    href: "a5",
  },
  {
    label: "Governing Law",
    href: "a6",
  },
  {
    label: "Changes",
    href: "a7",
  },
  {
    label: "Breaches of these terms of use",
    href: "a8",
  },
  {
    label: "Termination",
    href: "a9",
  },
];

export const TERMS_DATA = {
  TermsOfUse: {
    heading: [
      {
        title: "BisResume App",
      },
      {
        title: "Terms of Use",
      },
    ],
    data: [
      {
        text: `Thank you for choosing BisResume as your preferred service provider. We appreciate your support and are honored to have you as a customer.`,
      },
      {
        text: `Please take a moment to review these Terms of Use ("Terms," "Terms and Conditions") before utilizing our services (the "Website," the "Software," the "Service"). Your access to and use of our Service is conditioned upon your acceptance and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use our Service.`,
      },
      {
        text: `By accessing or using our Service, you agree to be bound by these Terms of Use. If you do not agree with any part of the Terms, we kindly ask that you refrain from using our Service.`,
      },
    ],
    description: `(Disclaimer: XYZ Company is a product of XYZ Company, LLC, meaning that the Terms of Use found below applies to our Service. When there is a reference to "XYZ Company," "us," or "we," this includes our website, app, service, software, and any other application or product directly related to XYZ Company and owned & developed by XYZ Company, LLC.)`,
  },
  TableOfContents: {
    heading: "Table of Contents:",
  },
  TheNovoresumeContent: {
    heading: "1. The BisResume Content",
    data: [
      {
        text: `All of the information, content, features, and functionality provided by XYZ Company, including but not limited to directories, guides, articles, reviews, text, photographs, images, illustrations, video, source and object code, software, data, and all other matters related to our Service (collectively, the "Content"), are protected under applicable copyrights and other proprietary (including but not limited to intellectual property) rights and are the property of XYZ Company.`,
      },
      {
        text: `You may not use any framing techniques or utilize framing techniques that involve any trademark, logo, copyrighted material, or other proprietary information (including images, text, page layout, or form) of XYZ Company without the express written consent of an authorized representative of XYZ Company. Additionally, you agree not to decompile, reverse engineer or disassemble any software or other products or processes available through our Service, not to insert any code or product or manipulate the Content of our Service in any way that affects the user's experience, and not to use any data mining, robots, cancelbots, Trojan horse, or any data gathering or extraction method in connection with your use of our Service.`,
      },
      {
        text: `XYZ Company respects the intellectual property of others. If you believe that your work has been copied in a way that constitutes copyright infringement or if you are aware of any infringing material placed on our Service, please contact us.`,
      },
      {
        text: `The information available on our Service is for general information purposes only. While we strive to do thorough research and keep the information up-to-date and accurate, we do not guarantee the completeness, accuracy, reliability, suitability or availability of the information. Any reliance on the information available is therefore at your own risk.`,
      },
    ],
  },
  AcceptableUse: {
    heading: "2. Acceptable Use",
    description: `As a user of XYZ platform, you agree to use the platform in a responsible and lawful manner. Specifically, you agree not to:`,
    data: [
      {
        text: `Cause damage to the platform or impair its availability or accessibility.`,
      },
      {
        text: `Use the platform for any unlawful, illegal, fraudulent or harmful purposes.`,
      },
      {
        text: `Copy, store, host, transmit, send, use, publish or distribute any material that contains malicious software.`,
      },
      {
        text: `Violate the copyright or proprietary rights of others.`,
      },
      {
        text: `Conduct any automated data collection activities without express written consent.`,
      },
      {
        text: `Use the platform to create resumes or other documents for third parties without explicit authorization.`,
      },
      {
        text: `Sell or trade any materials or documents generated by the platform to any third party.`,
      },
      {
        text: `Transmit or send unsolicited commercial communications.`,
      },
      {
        text: `Use the platform for marketing purposes without express written consent.`,
      },
      {
        text: `Use the platform if you are under 18 years of age.`,
      },
    ],
    lastDescription: `It is important to note that any violation of these terms of use may result in the suspension or termination of your account.`,
  },
  Security: {
    heading: "3. Security",
    data: `You acknowledge and understand that the transmission of data over the internet or other networks is not completely secure, and any information you transmit to BisResume may be intercepted or accessed by unauthorized parties. While BisResume has implemented commercially reasonable security measures to protect your personal information, we cannot guarantee the complete security of your information and will not be liable for any unauthorized access or use of your personal information. It is important for you to protect against unauthorized access to your account and information by selecting and protecting your password appropriately, and limiting access to your computer and browser by signing off after you have finished accessing your account.`,
  },
  LinksToOtherSoftware: {
    heading: "4. Links To Other Software/Websites/Services",
    description: `BisResume is not responsible for the content, privacy policies, or practices of any third-party software, websites, or services that may be linked to on the BisResume website. It also states that any dealings or transactions with advertisers on BisResume are solely between the user and the advertiser, and BisResume will not be held responsible for any loss or damage related to those dealings. Additionally, the text mentions that BisResume cannot be held liable for any issues that may arise from malicious software or viruses affecting the website, and advises users to protect their devices with antivirus software and to regularly check for any potential issues. The text also states that BisResume's team strives to provide professional and researched content, and in some cases this content may be provided by third-party software, websites, or services. Users are advised to read the terms of use and privacy policies of any third-party software, websites, or services that they visit.`,
  },
  WarrantyAndPremiumAccount: {
    heading: "5. Warranty and Premium Account",
    description: `BisResume provides its service and products on an "as is" and "as available" basis without any representations or warranties. The service may not be constantly available or meet all user requirements. BisResume reserves the right to change the design and structure of its products and services for improvement. If acting as a consumer, users have the right to cancel their purchase within 14 days and claim a refund. If there are technical issues during purchase, users should contact BisResume to have the problem investigated and possibly receive compensation or refund. BisResume may delete premium accounts if the user is misusing the service. Private details are encrypted for protection, and BisResume reserves the right to change prices for services due to promotions, taxes, or external factors.`,
  },
  GoverningLaw: {
    heading: "6. Governing Law",
    data: `These terms of service are governed and interpreted in accordance with the laws of Denmark and the European Union. BisResume reserves the right to enforce any rights outlined in these terms and failure to do so does not waive those rights. If any provision of these terms is deemed invalid or unenforceable by a court, the remaining provisions will remain in effect.`,
  },
  Changes: {
    heading: "7. Changes",
    data: `By continuing to access or use BisResume after those changes become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you should stop using BisResume. If you have any questions or concerns about these Terms, please contact us at `,
    href: "contact@bisResume.com",
  },
  BreachesOfTheseTermsOfUse: {
    heading: "8. Breaches of these terms of use",
    data: `At XYZ Company, we take the protection of our intellectual property very seriously. If it is found that any of our copyrighted material, trademarks, or proprietary information has been used without our express permission, we reserve the right to take legal action against the offending party. This includes, but is not limited to, seeking monetary damages, injunctions, and any other remedies available under the law. Furthermore, any unauthorized access or use of our protected information will be considered a violation of our terms of service and may result in termination of your account and/or access to our services. We strongly advise all users to respect our intellectual property rights and to seek proper authorization before using any of our protected materials.`,
  },
  Termination: {
    heading: "9. Termination",
    data: `BisResume also reserves the right to remove any content that is in violation of our terms of use, including but not limited to: copyrighted material, offensive language or images, and any content that is deemed to be harmful or illegal. Failure to comply with these guidelines may result in the termination of your account and potential legal action. We encourage our users to report any suspicious or inappropriate behavior to help maintain a safe and enjoyable experience for all.`,
  },
  ContactUs: {
    heading: "Contact Us",
    href: "contact@bisResume.com ",
    desIst: `At BisResume, we value the feedback of our users and are committed to providing a transparent and accurate service. Therefore, we encourage you to reach out to us if you have any concerns or suggestions regarding our Terms of Use. Our team can be reached at `,
    desLast: `and we will do our best to respond promptly. Additionally, we regularly review and update our Terms of Use to ensure they reflect the latest regulations and best practices. The date of the last modification was 03/Jan/2023 and we encourage you to review the Terms of Use periodically for any updates or changes.`,
  },
};
