import Image1 from '../../../../public/images/cms-media/copy-of-dark-green-minimalist-women-empowerment-instagram-post-10-.png'
import Image2 from '../../../../public/images/cms-media/copy-of-dark-green-minimalist-women-empowerment-instagram-post-10-.png'

export const blogData = [
    { slug: "test-blog", image: Image1, date: 'Dec 25, 2021', title: "Giving Developers a seat in the table", description: 'Software development is the most needed and most profitable business these days. Web and mobile apps have lots of possibilities, ......' },
    { slug: "test-blog", image: Image2, date: 'Dec 25, 2021', title: "Giving Developers a seat in the table", description: 'Software development is the most needed and most profitable business these days. Web and mobile apps have lots of possibilities, ......' },
    { slug: "test-blog", image: Image2, title: "Giving Developers a seat in the table", description: 'Software development is the most needed and most profitable business these days. Web and mobile apps have lots of possibilities, ......' },
    { slug: "test-blog", image: Image2, title: "Giving Developers a seat in the table", description: 'Software development is the most needed and most profitable business these days. Web and mobile apps have lots of possibilities, Software development is the most needed and most profitable business these days. Web and mobile apps have lots of possibilities,Software development is the most needed and most profitable business these days. Web and mobile apps have lots of possibilities, Software development is the most needed and most profitable business these days. Web and mobile apps have lots of possibilities, ......' },
    { slug: "test-blog", image: Image2, title: "Giving Developers a seat in the table", description: 'Software development is the most needed and most profitable business these days. Web and mobile apps have lots of possibilities,Software development is the most needed and most profitable business these days. Web and mobile apps have lots of possibilities,Software development is the most needed and most profitable business these days. Web and mobile apps have lots of possibilities, Software development is the most needed and most profitable business these days. Web and mobile apps have lots of possibilities, ......' },
    { slug: "test-blog", image: Image2, title: "Giving Developers a seat in the table", description: 'Software development is the most needed and most profitable business these days. Web and mobile apps have lots of possibilities, Software development is the most needed and most profitable business these days. Web and mobile apps have lots of possibilities,Software development is the most needed and most profitable business these days. Web and mobile apps have lots of possibilities, Software development is the most needed and most profitable business these days. Web and mobile apps have lots of possibilities, ......' },
    { slug: "test-blog", image: Image2, title: "Giving Developers a seat in the table", description: 'Software development is the most needed and most profitable business these days. Web and mobile apps have lots of possibilities,Software development is the most needed and most profitable business these days. Web and mobile apps have lots of possibilities,Software development is the most needed and most profitable business these days. Web and mobile apps have lots of possibilities, Software development is the most needed and most profitable business these days. Web and mobile apps have lots of possibilities, ......' },
]

