backend:
  name: github # our repository provider
  repo: M-Ahmad-Asghar/deployTest1 # username/repo
  branch: master # the main branch of our repo
  base_url: "https://app-bis-resume.vercel.app" # our site's base URL 
  auth_endpoint: "api/auth" # used together with base_url for our custom endpoints (more on this later)
media_folder: "public/images/cms-media" # the folder we want to upload new images to
public_folder: "/images/cms-media" # the folder our images should be fetched from
collections: # our content types, this is just an example!
  - name: "blogs"
    label: "Blog"
    folder: "_posts/blogs"
    create: true
    slug: "{{title}}"
    # media_folder: "../../public/images/blog-media" # the folder we want to upload new images to
    # public_folder: "/images/blog-media" # the folder our images should be fetched from
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" , required: true}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", required: true }
      - { label: "Category", name: "category", widget: "string", required: true }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: true}
      - { label: "Description", name: "description", widget: "string",pattern: ['.{20,}', "Must have at least 150 characters"], required: true }
      - { label: "Body", name: "body", widget: "markdown", required: true }

  - name: "techData"
    label: "Technologies"
    folder: "_posts/technologies"
    create: true
    slug: "{{title}}"
    # media_folder: "../../public/images/technologies-media"  
    # public_folder: "/images/technologies-media" 
    fields:
      - { label: "Category", name: "category", widget: "select", options: ["Website Development", "Mobile App Development", "Project Management", "Blockchain Development", "UI/UX Design",  "Digital Marketing"], required: true}
      - { label: "Tech Icon", name: "thumbnail", widget: "image", required: true}
      - { label: "Title", name: "title", widget: "string", required: true }
      
  - name: "portfolio"
    label: "Portfolio"
    folder: "_posts/portfolio"
    create: true
    slug: "{{title}}"
    # media_folder: "../../public/images/portfolio-media"  
    # public_folder: "/images/portfolio-media" 
    fields:
     - { label: "Thumbnail", name: "thumbnail", widget: "image", required: true}
     - { label: "Images List", name: "images", widget: "list",summary: '{{fields.image}}', field: {label: Image, name: image, widget: image} , required: true}
     - { label: "Title", name: "title", widget: "string", required: true }
     - { label: "Description", name: "description", widget: "text", required: true }
     - { label: "Completion Date", name: "completionDate", widget: "date", format: "MMM Do YY", required: true }
     - { label: "Project Type", name: "projectType", widget: "string", required: true }
     - { label: "Category", name: "category", widget: "string", required: true }
     - { label: "Video", name: "video", widget: "file", required: false }
     - { label: 'Color', name: 'color', widget: 'color', enableAlpha: true, allowInput: true, required: true }
     - { label: "Client Name", name: "clientName", widget: "string", required: true }
     - { label: "Link", name: "link", widget: "string", required: true }
     - { label: "Technology Stack", name: "techStack", widget: "list",summary: '{{fields.image}}', field: {label: Image, name: image, widget: image} , required: true}
     - { label: "Layout", name: "layout", widget: "hidden", default: "blog" , required: true}

  - name: "reviews"
    label: "Reviews"
    folder: "_posts/reviews"
    create: true
    slug: "{{clientName}}"
    # media_folder: "../../public/images/reviews-media"  
    # public_folder: "/images/reviews-media" 
    fields:
     - { label: "Client Name", name: "clientName", widget: "string", required: true}
     - { label: "Client Position", name: "clientPosition", widget: "string", required: true}
     - { label: "Review Date", name: "reviewDate", widget: "date", format: "MMM Do YY", required: true}
     - { label: "Review Description", name: "description", widget: "text", required: true}
     - { label: "Cover Image", name: "image", widget: "image", required: true}
  - name: "awardsAndClients"
    label: "Awards and Clients"
    folder: "_posts/awardsAndClients"
    create: true
    slug: "{{title}}"
    # media_folder: "../../public/images/awardsAndClients-media"  
    # public_folder: "/images/awardsAndClients-media" 
    fields:
     - { label: "Cover Image", name: "image", widget: "image", required: true}

  - name: "services"
    label: "Services"
    folder: "_posts/services"
    create: true
    slug: "{{title}}"
    # media_folder: "../../public/images/services-media"  
    # public_folder: "/images/services-media" 
    fields:
     - { label: "Icon", name: "icon", widget: "image", required: true}
     - { label: "Title", name: "title", widget: "string", required: true}
     - { label: "Description", name: "description", widget: "text", required: true}




     





