backend:
  name: github # our repository provider
  repo: adnan-guru/techloset/app-bis-resume # username/repo
  branch: master # the main branch of our repo
  base_url: "https://app-bis-resume.vercel.app" # our site's base URL 
  auth_endpoint: "api/auth" # used together with base_url for our custom endpoints (more on this later)
media_folder: "public/images/cms-media" # the folder we want to upload new images to
public_folder: "/images/cms-media" # the folder our images should be fetched from
collections: # our content types, this is just an example!
  - name: "blogs"
    label: "Blog"
    folder: "_posts/blogs"
    create: true
    slug: "{{title}}"
    # media_folder: "../../public/images/blog-media" # the folder we want to upload new images to
    # public_folder: "/images/blog-media" # the folder our images should be fetched from
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" , required: true}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", required: true }
      - { label: "Category", name: "category", widget: "string", required: true }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: true}
      - { label: "Description", name: "description", widget: "string",pattern: ['.{20,}', "Must have at least 150 characters"], required: true }
      - { label: "Body", name: "body", widget: "markdown", required: true }
