export const data = [
  {
    title: "Excellent and wonderfull",
    date: "April 1 2012",
    name: "Joshua",
    rating: 5,
    feedback: "He is very good and generous person",
  },
  {
    title: "Excellent and wonderfull",
    date: "April 1 2012",
    name: "Joshua",
    rating: 5,
    feedback: "He is very good and generous person",
  },
  {
    title: "Excellent and wonderfull",
    date: "April 1 2012",
    name: "Joshua",
    rating: 5,
    feedback: "He is very good and generous person",
  },
  {
    title: "Excellent and wonderfull",
    date: "April 1 2012",
    name: "Joshua",
    rating: 5,
    feedback: "He is very good and generous person",
  },
  {
    title: "Excellent and wonderfull",
    date: "April 1 2012",
    name: "Joshua",
    rating: 5,
    feedback: "He is very good and generous person",
  },
  {
    title: "Excellent and wonderfull",
    date: "April 1 2012",
    name: "Joshua",
    rating: 5,
    feedback: "He is very good and generous person",
  },
  {
    title: "Excellent and wonderfull",
    date: "April 1 2012",
    name: "Joshua",
    rating: 5,
    feedback: "He is very good and generous person",
  },
  {
    title: "Excellent and wonderfull",
    date: "April 1 2012",
    name: "Joshua",
    rating: 5,
    feedback: "He is very good and generous person",
  },
  {
    title: "Excellent and wonderfull",
    date: "April 1 2012",
    name: "Joshua",
    rating: 5,
    feedback: "He is very good and generous person",
  },
  {
    title: "Excellent and wonderfull",
    date: "April 1 2012",
    name: "Joshua",
    rating: 5,
    feedback: "He is very good and generous person",
  },
  {
    title: "Excellent and wonderfull",
    date: "April 1 2012",
    name: "Joshua",
    rating: 5,
    feedback: "He is very good and generous person",
  },
  {
    title: "Excellent and wonderfull",
    date: "April 1 2012",
    name: "Joshua",
    rating: 5,
    feedback: "He is very good and generous person",
  },
];
